---
title: "ally_scratch_work"
output: pdf_document
date: "2023-04-14"
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
library(tidyverse)
library(dplyr)
library(lubridate)
library(here)
library(tidycensus)
library(sf)
library(rgdal)
library(mapview)
library(leaflet)

census_api_key("76ed5ebd001e4ba14ba63363f8adecda35d2847b")

here()
```

## R Markdown
```{r attempt at tidy census, echo=TRUE}

carteret.shape <- get_decennial(state = "NC", 
                                county = "Carteret",
                                geography = "tract",
                                geometry = TRUE,
                                variables = "P1_003N",
                                year = 2020)

full.state.shape <- get_decennial(state = "NC", 
                                geography = "county",
                                geometry = TRUE,
                                variables = "P1_003N",
                                year = 2020)

#carteret.shape <- carteret.shape %>%
  #select(GEOID, geometry) %>%
  #mutate(TRACT = c("970503", "970601", "970401",
                                    #"970101", "970102", "970603",
                                    #"970402", "970703", "9702", 
                                    #"970403", "970704", "970806",
                                    #"970502", "970804", "970903",
                                    #"970805", "970304", "970602",
                                    #"970103", "970702", "970904", 
                                    #"971003", "970606", "970301",
                                    #"970701", "970504", "970501", "970801", 
                                    #"970305", "971103"))
  
  
  
map1 <- ggplot(carteret.shape) +
  geom_sf()
print(map1)

map2 <-ggplot(full.state.shape) +
  geom_sf()
print(map2)

#writeOGR to save shapefiles ? 

#writeOGR(carteret.shape, file = here("./Data/Processed/carteretbytract.shp"))

write_csv(carteret.shape, file = 
            here("./Data/Processed/Carteret_county_bytract.csv"))
write_csv(full.state.shape, file = 
            here("./Data/Processed/NC_by_county.csv"))

carteret.tracts <-read_csv(here("./Data/Raw/carteret_tracts_.csv"))

carteret.sf <- carteret.tracts %>%
  st_as_sf(coords = c("INTPTLON", "INTPTLAT"), 
           crs = 4269)
ggplot(data = carteret.sf) +
  geom_sf()

mapview(carteret.sf)

#please_work <- st_read(read('./Data/Raw/carteret_tracts.shp'))
#mapview(please_work)

#st_write(please_work, here("./Data/Processed/carteret_tracts.shp"))

#carteret_shape_correct <- st_read(read('./Data/Processed/carteret_tracts.shp'))

#mapview(carteret_shape_correct)

#ggplot(data = carteret_shape_correct) +
  geom_sf()
```

```{r attempt at wrangling census csvs}

carteret.demo <-read_csv(here("Data/Raw/ACSDP5Y2021.DP05-race-age-sex.csv"))

carteret.age.sex <- carteret.demo %>%
  select(1,4,5,7:20) %>%
  filter(!row_number() %in% c(1, 2, 63:68))

colnames(carteret.age.sex) <- c("Census Tract", "Male", "Female", "Under 5 years",
                                "5 to 9 years", "10 to 14 years", "15 to 19 years",
                                "20 to 24 years", "25 to 34 years", "35 to 44 years",
                                "45 to 54 years", "55 to 59 years", "60 to 64 years",
                                "65 to 74 years", "75 to 84 years", "85 years and over",
                                "Median age (years)")

carteret.age.sex <- carteret.age.sex %>%
  mutate("Census Tract" = c("970101","970101","970102","970102","970103","970103","9702","9702","970301","970301","970304","970304","970305","970305","970401","970401","970402","970402","970403","970403","970501","970501","970502","970502","970503","970503","970504","970504","970601","970601","970602","970602","970603","970603","970606","970606","970701","970701","970702","970702","970703","970703","970704","970704","970801","970801","970804","970804","970805","970805","970806","970806", "970903", "970903","970904","970904","971003","971003","971103","971103"))

data.type <- c("Estimate", "Percent")
rep.data.type <- rep(data.type, times = 30)

carteret.age.sex <- carteret.age.sex %>%
  mutate("Data Type" = c(rep.data.type)) %>%
  select("Data Type", everything())

write_csv(carteret.age.sex, file = here("Data/Processed/Carteret.age.sex.csv"))

carteret.race <- carteret.demo %>%
  select(1, 40, 41, 42, 43, 46, 47, 48, 49, 50) %>%
  filter(!row_number() %in% c(1, 2, 63:68))

colnames(carteret.race) <- c("Census Tract", "White", "Black or African American",
                            "American Indian and Alaska Native", "Cherokee Tribal Grouping",
                            "Sioux Tribal Grouping", "Asian", "Asian Indian", 
                            "Chinese", "Filipino")

carteret.race <- carteret.race %>%
  mutate("Census Tract" = c("970101", "970101", "970102", "970102", "970103",
                            "970103", "9702", "9702", "970301",
                            "970301", "970304", "970304", "970305", "970305",
                            "970401", "970401", "970402", "970402", "970403",
                            "970403", "970501", "970501", "970502", "970502",
                            "970503", "970503", "970504", "970504", "970601",
                            "970601", "970602", "970602", "970603", "970603",
                            "970606", "970606", "970701", "970701", "970702",
                            "970702", "970703", "970703", "970704", "970704",
                            "970801", "970801", "970804", "970804", "970805",
                            "970805", "970806", "970806", "970903", "970903",
                            "970904", "970904", "971003", "971003", "971103",
                            "971103"))

carteret.race <- carteret.race %>%
  mutate("Data Type" = c(rep.data.type)) %>%
  select("Data Type", everything())

write_csv(carteret.race, file = here("Data/Processed/Carteret.race.csv"))

carteret.poverty <- read_csv(here("Data/Raw/ACSST5Y2021.poverty.csv"))

carteret.poverty <- carteret.poverty %>%
  select(1, 2, 4, 8, 12) %>%
  filter(!row_number() %in% c(1, 2, 3, 94:102))

colnames(carteret.poverty) <- c("Census Tract", 
                                "Population for Whom Poverty Status is Determined",
                                "Under 18 years", "18 to 64 years", 
                                "65 years and over")

carteret.poverty <- carteret.poverty %>%
  mutate("Census Tract" = c("970101", "970101", "970101", "970102", "970102", "970102",
                            "970103", "970103",
                            "970103", "9702", "9702", "9702", "970301",
                            "970301", "970301", "970304", "970304", "970304",
                            "970305", "970305", "970305", "970401",
                            "970401", "970401", "970402", "970402", "970402",
                            "970403", "970403",
                            "970403", "970501", "970501", "970501", "970502", 
                            "970502", "970502", "970503",
                            "970503", "970503", "970504", "970504", "970504",
                            "970601", "970601",
                            "970601", "970602", "970602", "970602", "970603", 
                            "970603", "970603", "970606",
                            "970606", "970606", "970701", "970701", "970701",
                            "970702", "970702",
                            "970702", "970703", "970703", "970703", "970704", 
                            "970704", "970704", "970801",
                            "970801", "970801", "970804", "970804", "970804",
                            "970805", "970805",
                            "970805", "970806", "970806", "970806", "970903", 
                            "970903", "970903", "970904",
                            "970904", "970904", "971003", "971003", "971003",
                            "971103", "971103", "971103"))

pov.list <-c("Total Estimate", "Below Poverty Level", "Percent Below Poverty Level")
rep.pov.list <- rep(pov.list, times = 30)

carteret.poverty <- carteret.poverty %>%
  mutate("Data Type" = c(rep.pov.list)) %>%
  select("Data Type", everything())

write_csv(carteret.poverty, file = here("Data/Processed/Carteret.poverty.csv"))

carteret.employment <- read_csv(here("Data/Raw/ACSST5Y2021.poverty.csv"))

carteret.employment <- carteret.employment %>%
  select(1, 33:39) %>%
  filter(!row_number() %in% c(1, 2, 3, 94:102))

colnames(carteret.employment) <- c("Census Tract", "Civilian Labor Force 16 Years and Over", "Employed", "Male","Female", "Unemployed", "U_Male", "U_Female")

carteret.employment <- carteret.employment %>%
  mutate("Census Tract" = c("970101", "970101", "970101", "970102", "970102", "970102",
                            "970103", "970103",
                            "970103", "9702", "9702", "9702", "970301",
                            "970301", "970301", "970304", "970304", "970304",
                            "970305", "970305", "970305", "970401",
                            "970401", "970401", "970402", "970402", "970402",
                            "970403", "970403",
                            "970403", "970501", "970501", "970501", "970502", 
                            "970502", "970502", "970503",
                            "970503", "970503", "970504", "970504", "970504",
                            "970601", "970601",
                            "970601", "970602", "970602", "970602", "970603", 
                            "970603", "970603", "970606",
                            "970606", "970606", "970701", "970701", "970701",
                            "970702", "970702",
                            "970702", "970703", "970703", "970703", "970704", 
                            "970704", "970704", "970801",
                            "970801", "970801", "970804", "970804", "970804",
                            "970805", "970805",
                            "970805", "970806", "970806", "970806", "970903", 
                            "970903", "970903", "970904",
                            "970904", "970904", "971003", "971003", "971003",
                            "971103", "971103", "971103"))

carteret.employment <- carteret.employment %>%
  mutate("Data Type" = c(rep.pov.list)) %>%
  select("Data Type", everything())

write_csv(carteret.employment, file = 
           here("./Data/Processed/Carteret.Employment.csv"))

carteret.education <- read_csv(here("Data/Raw/ACSST5Y2021.poverty.csv"))

carteret.education <- carteret.education %>%
  select(1, 27:31) %>%
  filter(!row_number() %in% c(1, 2, 3, 94:102))

carteret.education <- carteret.education %>%
  mutate("Label (Grouping)" = c("970101", "970101", "970101", "970102", "970102", "970102",
                            "970103", "970103",
                            "970103", "9702", "9702", "9702", "970301",
                            "970301", "970301", "970304", "970304", "970304",
                            "970305", "970305", "970305", "970401",
                            "970401", "970401", "970402", "970402", "970402",
                            "970403", "970403",
                            "970403", "970501", "970501", "970501", "970502", 
                            "970502", "970502", "970503",
                            "970503", "970503", "970504", "970504", "970504",
                            "970601", "970601",
                            "970601", "970602", "970602", "970602", "970603", 
                            "970603", "970603", "970606",
                            "970606", "970606", "970701", "970701", "970701",
                            "970702", "970702",
                            "970702", "970703", "970703", "970703", "970704", 
                            "970704", "970704", "970801",
                            "970801", "970801", "970804", "970804", "970804",
                            "970805", "970805",
                            "970805", "970806", "970806", "970806", "970903", 
                            "970903", "970903", "970904",
                            "970904", "970904", "971003", "971003", "971003",
                            "971103", "971103", "971103"))

carteret.education <- carteret.education %>%
  mutate("Data Type" = c(rep.pov.list)) %>%
  select("Data Type", everything())

write_csv(carteret.education, file = 
            here("./Data/Processed/carteret.education.csv"))

```

